version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
#      - aws s3 cp s3://ahjsp2/application.properties ./src/main/resources/application.properties

  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.jar ./Project_2.jar
  post_build:
    commands:
      - echo Build completed on `date`
      - Project_2.jar -d artifact/

artifacts:
  files:
    - target/Project_2.jar
  name: artifact