version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:

  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.war ./Project_2.war
  post_build:
    commands:
      - echo Build completed on `date`
      - unzip Project_2.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact