server:
  port: 5000 # Port 5000 because AWS Elastic Beanstalk expects for JAR packaged Java apps to listen on this port.

spring:
  application:
    name: jash

db:
  ipAddress: 35.153.17.108
  port: 27017
  dbName: p2
  username: admin
  password: revature

encrypt:
  salt: pepperedpotatos

jwt:
  header: Authorization
  prefix: "Bearer "
  secret: Revature
  expiration: 86400000
